export const ADD_PRODUCT_CART='ADD_PRODUCT_CART';

export const GET_NUMBERS_CART='GET_NUMBERS_CART';

export const DELETE_NUMBERS_CART='DELETE_NUMBERS_CART';

export const INCREASENUMBER='INCREASENUMBER';

export const DECREASENUMBER='DECREASENUMBER';

export const DELETE_PRODUCTS='DELETE_PRODUCTS';
export const CHECKOUT='CHECKOUT';

export const GET_CART_TOTAL='GET_CART_TOTAL';
